#ifndef SCE_IR_HELPER_H_
#define SCE_IR_HELPER_H_
#include "sce_basic_api.h"
#define SET_SCE_BINARY_MACHINE_TYPE(CONVERT_FUNC)\
CONVERT_FUNC(E_SCE_BINARY_INST_MOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_RMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_MMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_CMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_BMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_IMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_FMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_VMOV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_NAME__),\
CONVERT_FUNC(E_SCE_BINARY_INST_ADD__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SUB__),\
CONVERT_FUNC(E_SCE_BINARY_INST_MUL__),\
CONVERT_FUNC(E_SCE_BINARY_INST_DIV__),\
CONVERT_FUNC(E_SCE_BINARY_INST_MOD__),\
CONVERT_FUNC(E_SCE_BINARY_INST_AND__),\
CONVERT_FUNC(E_SCE_BINARY_INST_OR__),\
CONVERT_FUNC(E_SCE_BINARY_INST_XOR__),\
CONVERT_FUNC(E_SCE_BINARY_INST_NOT__),\
CONVERT_FUNC(E_SCE_BINARY_INST_NOTL__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SHR__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SHL__),\
CONVERT_FUNC(E_SCE_BINARY_INST_EQ__),\
CONVERT_FUNC(E_SCE_BINARY_INST_NEQ__),\
CONVERT_FUNC(E_SCE_BINARY_INST_LS__),\
CONVERT_FUNC(E_SCE_BINARY_INST_GT__),\
CONVERT_FUNC(E_SCE_BINARY_INST_LSEQ__),\
CONVERT_FUNC(E_SCE_BINARY_INST_GTEQ__),\
CONVERT_FUNC(E_SCE_BINARY_INST_TEST__),\
CONVERT_FUNC(E_SCE_BINARY_INST_RET__),\
CONVERT_FUNC(E_SCE_BINARY_INST_CALL__),\
CONVERT_FUNC(E_SCE_BINARY_INST_JMP__),\
CONVERT_FUNC(E_SCE_BINARY_INST_PHASE__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SYSTEM_CALL__),\
CONVERT_FUNC(E_SCE_BINARY_INST_BUILT_IN_CALL__),\
CONVERT_FUNC(E_SCE_BINARY_INST_LABEL__),\
CONVERT_FUNC(E_SCE_BINARY_INST_ALLOC__),\
CONVERT_FUNC(E_SCE_BINARY_INST_NAME_REPEAT__),\
CONVERT_FUNC(E_SCE_BINARY_INST_STACK_POINT__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SUB_STACK_POINT__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SAVE_REGISTER__),\
CONVERT_FUNC(E_SCE_BINARY_INST_LOAD_REGISTER__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SAVE_REGISTER_STACK__),\
CONVERT_FUNC(E_SCE_BINARY_INST_LOAD_REGISTER_STACK__),\
CONVERT_FUNC(E_SCE_BINARY_INST_ADD_STACK__),\
CONVERT_FUNC(E_SCE_BINARY_INST_SUB_STACK__),\
CONVERT_FUNC(E_SCE_BINARY_INST_DELETE_REGISTER__),
typedef enum Sce_Binary_Instruction {
	SET_SCE_BINARY_MACHINE_TYPE(CONVERT_DEFINE)
}Sce_Binary_Instruction;

typedef struct Sce_Binary_Machine_Instructions {
	struct Sce_Binary_Machine_Instructions* next;
	Sce_Binary_Instruction sce_bmr_code;

	uint32_t ope1;
	union {
		uint32_t ope2;
		int64_t icope2;
		uint8_t ccope2;
		uint8_t* scope2;
		void* vcope2;
		float fcope2;
		double dcope2;
		bool bcope2;
	};
}Sce_Binary_Machine_Instructions;

#define SCE_VIRTUAL_REGISTER_MAX 127
#define SCE_VIRTUAL_GENERAL_REGISTER_MAX 128
#define SCE_VIRTUAL_REGISTER_RETURN SCE_VIRTUAL_GENERAL_REGISTER_MAX
#define SCE_VIRTUAL_REGISTER_CMP_RETURN SCE_VIRTUAL_REGISTER_RETURN
#define SCE_VIRTUAL_REGISTER_MAX_ 129
#define SCE_VIRTUAL_STACK_MIN SCE_VIRTUAL_REGISTER_MAX_
#define GET_SCE_STACK_START_OFFSET(idx) idx - SCE_VIRTUAL_STACK_MIN

#endif